### PR TITLE
feat: implement sessions using an encrypted cookie

### PR DESCRIPTION
**Pull request by bstrie**
Supercedes #104.

This should be transparent to the user. The main benefits are as
follows:

1. User sessions can last beyond service restarts. In order to enable
   this, the `--session-key` option must be used to provide a persistent
   encryption key.

2. Simpler structure with far fewer locks. This should avoid accidental
   lock contention.

Signed-off-by: bstrie <865233+bstrie@users.noreply.github.com>

### CODE REVIEW

**Comment by bstrie** [comment]
Not sure what nix magic I need to do in order to get the CI to pass.

**Comment by definitelynobody** [comment]
https://github.com/cargo2nix/cargo2nix#run-it-now

```
nix develop github:cargo2nix/cargo2nix#bootstrap --extra-experimental-features nix-command --extra-experimental-features flakes
cargo2nix
exit
```

should work i think

**Review by definitelynobody — APPROVED** [review]

**Comment by puiterwijk** [comment]
Yeah, you want to run `nix run --extra-experimental-features nix-command --extra-experimental-features flakes github:cargo2nix/cargo2nix`, and commit the resulting Cargo.nix.

**Comment by rvolosatovs** [comment]
As mentioned earlier, the required patch is uploaded as an artifact to the lint job https://github.com/profianinc/benefice/actions/runs/2860479651 and also conveniently printed to the log.
I am working on migrating to a build system, which does not require code generation meanwhile

**Pull request closed without merging**
