### PR TITLE
fix: prevent old output appearing when restarting jobs

### LINKED ISSUE #137: Restarting workloads quickly may show old output
When getting the output of a workload the previously running one because it hasn't been completely stopped yet. To fix this the output should be retrieved using the uuid of the running workload.

### PR DESCRIPTION
**Pull request by definitelynobody**
Closes #137

### CODE REVIEW

**Review by rvolosatovs — CHANGES_REQUESTED** [review]
This change will be obsoleted by the PR I will open tomorrow morning, requesting changes to prevent merge

**Review by rvolosatovs — COMMENTED** [review]
I think the changes actually mostly look good, please rebase and re-request review

**Review by rvolosatovs — COMMENTED** [review]
desired changes discussed offline (instead of passing ID from the frontend, store the last-known ID in the frontend and flush the terminal if it changes as a result of a new fetch)

**Review by bstrie — APPROVED** [review]

**Comment by rvolosatovs** [comment]
@bstrie @definitelynobody this PR is now merged, but the discussed changes were not addressed, job ID is still a required parameter for getting output and it should not be. Please file an issue and fix in a follow-up

**Pull request merged**
